[package]
description = "Conflux utilities library"
homepage = "http://www.conflux-chain.org"
license = "GPL-3.0"
name = "cfx-utils"
version = "1.0.0"
edition = "2018"

[dependencies]
log = "0.4"
parking_lot = "0.10"
