[package]
name = "state-sync"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem state synchronizer (state sync)"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bcs = "0.1.2"
fail = "0.4.0"
futures = "0.3.12"
itertools = { version = "0.10.0", default-features = false }
once_cell = "1.7.2"
proptest = { version = "1.0.0", optional = true }
rand = "0.8.3"
serde = { version = "1.0.124", default-features = false }
thiserror = "1.0.24"
tokio = { version = "1.3.0", features = ["full"] }
tokio-stream = "0.1.4"

channel = { path = "../common/channel" }
diem-config = { path = "../config" }
diem-crypto = { path = "../crypto/crypto" }
diem-infallible = { path = "../common/infallible" }
diem-logger = { path = "../common/logger" }
diem-metrics = { path = "../common/metrics" }
diem-proptest-helpers = { path = "../common/proptest-helpers", optional = true }
diem-temppath = { path = "../common/temppath" }
diem-types = { path = "../types" }
diemdb = { path = "../storage/diemdb", optional = true }
executor = { path = "../consensus/executor" }
executor-types = { path = "../types/executor-types" }
storage-interface = { path = "../storage/storage-interface" }
subscription-service = { path = "../common/subscription-service" }

[dev-dependencies]
bytes = "1.0.1"
proptest = "1.0.0"

channel = { path = "../common/channel" }
diem-crypto = { path = "../crypto/crypto" }
diem-proptest-helpers = { path = "../common/proptest-helpers" }
diemdb = { path = "../storage/diemdb" }
storage-service = { path = "../storage/storage-service" }
subscription-service = { path = "../common/subscription-service" }
diem-time-service = { path = "../common/time-service", features = ["testing"] }

[features]
default = []
failpoints = ["fail/failpoints"]
fuzzing = ["proptest", "diem-config/fuzzing",  "diem-types/fuzzing", "diem-proptest-helpers"]
