[package]
name = "cfx-types"
version = "0.1.0"
license = "GPL-3.0"
description = "Conflux types"

[dependencies]
ethereum-types = "0.9"
serde_derive = "1.0"
serde = "1.0"

[features]
storage_benchmark_no_account_space_check = []
