[package]
name = "pow-types"
version = "0.1.0"
authors = ["Peilun Li <peilun.li@conflux-chain.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfx-types = {path = "../../../../../cfx_types"}
diem-types = {path = ".."}
async-trait = "0.1"
