base:
  #data_dir: ./pos_db
  role: validator
  waypoint:
    from_config: 0:30a11f5e6da6dbaa4cf86e81796eb3a3715419cd0a78ec5c1c207e94f1c48263
consensus:
  round_initial_timeout_ms: 60000
  safety_rules:
    service:
      type: local
execution:
  genesis_file_location: ./genesis_file
logger:
  file: ./pos.log
  level: TRACE
#storage:
  #dir: ./pos_db/db
