
base:
  #data_dir: ./pos_db
  role: validator
  waypoint:
    from_config: 0:0ce1d1370b5fda09694fe5a5362addd929f46c335818086b86d5596613f3ae19
consensus:
  round_initial_timeout_ms: 60000
  safety_rules:
    service:
      type: local
execution:
  genesis_file_location: ./genesis_file
logger:
  file: ./pos.log
  level: DEBUG
#storage:
  #dir: ./pos_db/db
