base:
  #data_dir: ./pos_db
  role: validator
  waypoint:
    from_config: 0:6c1fc20a6cd4cd5ea5f02f12837c01b723286210da3b7c781bec5ff0544ff032
consensus:
  round_initial_timeout_ms: 60000
  safety_rules:
    service:
      type: local
execution:
  genesis_file_location: ./genesis_file
logger:
  file: ./pos.log
  level: TRACE
#storage:
  #dir: ./pos_db/db
