
base:
  #data_dir: ./pos_db
  role: validator
  waypoint:
    from_config: 0:161884893bc663cddf268f0ddfd3c928af506e22094888f15dfab69d48cb48b3
consensus:
  round_initial_timeout_ms: 60000
  safety_rules:
    service:
      type: local
execution:
  genesis_file_location: ./genesis_file
logger:
  file: ./pos.log
  level: TRACE
#storage:
  #dir: ./pos_db/db
