
base:
  #data_dir: ./pos_db
  role: validator
  waypoint:
    from_config: 0:12986d502ca90c04a98152842e30d881d760e9823cf6822bce84c8f742d69b45
consensus:
  round_initial_timeout_ms: 60000
  safety_rules:
    service:
      type: local
execution:
  genesis_file_location: ./genesis_file
logger:
  file: ./pos.log
  level: DEBUG
#storage:
  #dir: ./pos_db/db
