base:
  #data_dir: ./pos_db
  role: validator
  waypoint:
    from_config: 0:60b5e8190af0535f1cf6a2701decb556d5cb93a8477c0eb053c7d0e42e0dedb2
consensus:
  round_initial_timeout_ms: 60000
  safety_rules:
    service:
      type: local
execution:
  genesis_file_location: ./genesis_file
logger:
  file: ./pos.log
  level: TRACE
#storage:
  #dir: ./pos_db/db
