
base:
  #data_dir: ./pos_db
  role: validator
  waypoint:
    from_config: 0:d7b2734d30a64d52ab5b2f29e6c5e11f911889c43d8af8c6e526214057a0827c
consensus:
  round_initial_timeout_ms: 60000
  safety_rules:
    service:
      type: local
execution:
  genesis_file_location: ./genesis_file
logger:
  file: ./pos.log
  level: DEBUG
#storage:
  #dir: ./pos_db/db
