
base:
  #data_dir: ./pos_db
  role: validator
  waypoint:
    from_config: 0:ff5051ec1267c9c49fbb1b3d07afcfddb925aa75ed4988a7610e5d33db9afb72
consensus:
  round_initial_timeout_ms: 60000
  safety_rules:
    service:
      type: local
execution:
  genesis_file_location: ./genesis_file
logger:
  file: ./pos.log
  level: DEBUG
#storage:
  #dir: ./pos_db/db
