
base:
  #data_dir: ./pos_db
  role: validator
  waypoint:
    from_config: 0:d190dcf8575f2ae6952dc7749aedb347f8aef0aa392ffaef0fca6836d7294954
consensus:
  round_initial_timeout_ms: 60000
  safety_rules:
    service:
      type: local
execution:
  genesis_file_location: ./genesis_file
logger:
  file: ./pos.log
  level: DEBUG
#storage:
  #dir: ./pos_db/db
